version: "3.1"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - api
  client:
    container_name: client
    restart: always
    stdin_open: true
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes: 
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    depends_on: 
      - api
  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes: 
      - ./api:/usr/src/api
      - /usr/src/api/node_modules      
